general {
    lock_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Keyboard Backlight Timeout Handler (Razer Integration)
listener { 
    timeout = 150
    on-timeout = razer-cli -b 0
    on-resume = razer-cli -b 100
}

# Display Session Locking Threshold
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Screen Power Saving (DPMS) Rules
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# Full Suspend Boundary Threshold
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
