# #######################################################################################
# WINDOWS AND WORKSPACES RULES
# #######################################################################################

# Global Window Rules (Targeted matches using class strings)
windowrule = opacity 0.9, match:class kitty

windowrule = workspace 9 silent, match:class org.keepassxc.KeePassXC
windowrule = workspace 8 silent, match:class steam, match:title Steam
windowrule = workspace 2 silent, match:class discord
windowrule = workspace 3 silent, match:class brave-browser

# Specialized Application Layout Hooks
windowrule {
    name = move-Steam
    match:class = steam
    match:title = Steam Big Picture Mode
    monitor = 0
}

windowrule {
    name = move-KeepassXC-Popup
    match:initial_class = org.keepassxc.KeePassXC
    center = on
}

# NOTE: Monitor workspace assignments (e.g., workspace = 2, monitor:DP-2) 
# have been moved entirely into your local 'monitors.conf' so they don't crash your laptop profile.



